version: '3.6'
services:
  chickenrun:
    image: edevouge/chickenrun:latest
    restart: always
    volumes:
      - ./chickenrun.conf:/etc/chickenrun/
    environment:
      - CHICKENRUN_CONF_PATH=/etc/chickenrun/chickenrun.conf
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    logging:
      options:
        max-file: "1"
        max-size: "1g"

  netdata:
    image: netdata/netdata
    restart: always
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-file: "1"
        max-size: "1g"
