version: '3.6'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always 
    expose:
      - "1883"
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/auth:/mosquitto/config/auth
      - ./data:/mosquitto/data
      - ./certs:/mosquitto/certs
    logging:
      options:
        max-file: "1"
        max-size: "1g"

  netdata:
    image: netdata/netdata
    restart: always 
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-file: "1"
        max-size: "1g"
